"""Build an offline app shell with a content-versioned, scoped service worker."""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
FONT = 'https://raw.githubusercontent.com/google/fonts/main/ofl/notosansjp/NotoSansJP%5Bwght%5D.ttf'


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--base-href', default='/')
    parser.add_argument('--skip-build', action='store_true')
    args = parser.parse_args()
    if not args.base_href.startswith('/') or not args.base_href.endswith('/'):
        parser.error('--base-href must start and end with /')
    if not args.skip_build:
        subprocess.run(['flutter', 'build', 'web', '--release', '--no-web-resources-cdn',
                        '--pwa-strategy=none', f'--base-href={args.base_href}'], cwd=ROOT, check=True)
    output = ROOT / 'build/web'
    files = sorted(p for p in output.rglob('*') if p.is_file()
                   and p.name not in ('service-worker.js', 'flutter_service_worker.js', '.DS_Store')
                   and not p.name.endswith('.map'))
    digest = hashlib.sha256()
    for path in files:
        digest.update(path.relative_to(output).as_posix().encode())
        digest.update(path.read_bytes())
    version = digest.hexdigest()[:16]
    assets = [p.relative_to(output).as_posix() for p in files]
    worker = '''// Generated by tool/build_pwa.py; only app assets, never map tiles.
const VERSION = __VERSION__;
const PREFIX = 'birdlog_app_webversion:' + self.registration.scope + ':';
const CACHE = PREFIX + VERSION;
const LOCAL = __ASSETS__;
const FONT = __FONT__;
const URLS = [...LOCAL.map(p => new URL(p, self.registration.scope).href), FONT];
self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    try {
      // Bounded parallel batches avoid a request storm on mobile connections.
      for (let i = 0; i < URLS.length; i += 6) {
        await Promise.all(URLS.slice(i, i + 6).map(async url => {
          const response = await fetch(new Request(url, {cache: 'reload'}));
          if (!response.ok) throw new Error('Precache failed: ' + url);
          await cache.put(url, response);
        }));
      }
    } catch (error) { await caches.delete(CACHE); throw error; }
  })());
  // No skipWaiting: never replace app code while a user is recording.
});
self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    for (const name of await caches.keys()) {
      if (name.startsWith(PREFIX) && name !== CACHE) await caches.delete(name);
    }
    await self.clients.claim();
  })());
});
self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  const home = new URL(self.registration.scope);
  if (req.mode === 'navigate' && url.origin === home.origin && url.pathname.startsWith(home.pathname)) {
    event.respondWith(caches.open(CACHE).then(async cache =>
      (await cache.match(new URL('index.html', home).href)) || fetch(req)));
  } else if (URLS.includes(url.href)) {
    event.respondWith(caches.open(CACHE).then(async cache => (await cache.match(req)) || fetch(req)));
  }
  // Cross-origin map requests retain normal HTTP caching / provider expiry.
});
'''.replace('__VERSION__', json.dumps(version)).replace('__ASSETS__', json.dumps(assets)).replace('__FONT__', json.dumps(FONT))
    (output / 'service-worker.js').write_text(worker)
    (output / '.nojekyll').touch()
    print(f'PWA ready: {output} ({len(files)} assets, version {version})')


if __name__ == '__main__':
    main()
